"""Delete duplicated ban_id

Revision ID: 6310c84b1db2
Revises: ff03fd80382c
Create Date: 2022-04-29 14:01:42.901886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6310c84b1db2'
down_revision = 'ff03fd80382c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banned_users', 'ban_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banned_users', sa.Column('ban_id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
