"""comments

Revision ID: 710796831bc7
Revises: 6310c84b1db2
Create Date: 2022-04-30 03:08:21.772011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710796831bc7'
down_revision = '6310c84b1db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
