"""add name

Revision ID: b43db533e969
Revises: 6cfdb19665f6
Create Date: 2022-04-11 17:15:44.055421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43db533e969'
down_revision = '6cfdb19665f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'item_name')
    # ### end Alembic commands ###
